#!/bin/sh

set -e

CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}/journal"
DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}/journal"

# shellcheck source=/dev/null
[ -r "$CONFIG_HOME/config" ] && . "$CONFIG_HOME/config"

: "${JOURNAL_DATA:=$DATA_HOME}"
: "${JOURNAL_EDITOR:=$EDITOR}"
: "${JOURNAL_EDITOR:=$VISUAL}"
: "${JOURNAL_EDITOR:=vim}"

help() {
	cat <<-EOF
		Usage: ${0##*/} [-h] [-l] [-r JOURNAL] [JOURNAL]

		  -h display this help and exit
		  -l list journals
		  -r remove journal
	EOF
}

usage() {
	help | head -1
}

list_journals() {
	find -s "$JOURNAL_DATA" -depth 1 -type f -exec basename -- {} .md \;
}

remove() {
	rm -i "$JOURNAL_DATA/$1.md"
}

while getopts "hlr:" opt; do
	case "$opt" in
	h)
		help
		exit 0
		;;
	l)
		list_journals
		exit 0
		;;
	r)
		remove "$OPTARG"
		exit $?
		;;
	*)
		usage
		exit 1
		;;
	esac
done

shift $((OPTIND - 1))

# List journals if no options/arguments where passed in.
if [ -z "$1" ]; then
	list_journals
	exit 0
fi

[ -d "$JOURNAL_DATA" ] || mkdir -p "$JOURNAL_DATA"

$JOURNAL_EDITOR "$JOURNAL_DATA/$1.md"
